baseURL = 'https://ai-tech-blog-97e.pages.dev/'
defaultContentLanguage = 'ja'
title = 'AI・テック専門メディア'
theme = 'PaperMod'
ignoreLogs = ['warning-goldmark-raw-html']

[languages.ja]
  locale = 'ja-JP'
  weight = 1

[params]
  defaultTheme = 'auto'
  ShowToc = true
  TocOpen = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ['HTML', 'RSS', 'JSON']
